version: '3'
services:
  db:
    image: mysql:5.5
    container_name: 'btl_ltw_db'
    ports:
      - "3307:3307"
    volumes:
      - ./db:/var/lib/mysql/data
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: btl-ltw
      MYSQL_PASSWORD: root
